hash-format = "sha256"

[[files]]
file = "config/fancymenu/assets/mac.icns"
hash = "21ba2fd9a3603afaa0e5393b46278932923b769ffe06ed030717dfa9c67c9085"

[[files]]
file = "config/fancymenu/assets/x16.png"
hash = "77429627e11031fd3690fb990f8ac5e9a9142052884dc46009616c71130da57a"

[[files]]
file = "config/fancymenu/assets/x32.png"
hash = "656bed501b8595062e0012940e853b85b606592f105a37635119c7904e2eb93a"

[[files]]
file = "config/fancymenu/custom_gui_screens.txt"
hash = "ff492043eaf454c46e949d5eef32ece90cc5a19feb50a161dd29a43b5732c880"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "a474ea7af5a5f1e5b18ebf6838cf75db9fbad4227460e4572f2bfd9838d276d9"

[[files]]
file = "config/fancymenu/customization/drippy_loading_overlay_layout.txt"
hash = "59d4aa0c3ee7c10d2bb73fd00880a113c6ebbda6cf09f8fef122a8b6ab115ea3"

[[files]]
file = "config/fancymenu/customization/title_screen_layout.txt"
hash = "dd626782dfabe324d7134627cd680e5be6d539a83853b34ebae429558354f190"

[[files]]
file = "config/fancymenu/layout_editor/widgets/element_layer_control.lewidget"
hash = "051d700ea7ff1bd626063d60f9a9cd65a0af1fed5903706d1e70fce20bcb2495"

[[files]]
file = "config/fancymenu/legacy_checklist.txt"
hash = "9a25d3dc708e43eabafce5479a13c02dae15bc7f673afb2745b8b2ba48a97dc0"

[[files]]
file = "config/fancymenu/options.txt"
hash = "7085b29bea9d3bcbf60d815a8ede457d8af627f1384c9e9fc02af586b5d06726"

[[files]]
file = "config/fancymenu/ui_themes/dark.json"
hash = "3f1263eaf693fdb6a315099b06797ac18830faa66c620916a80337a5082fd850"

[[files]]
file = "config/fancymenu/ui_themes/light.json"
hash = "3fcfc5f9957fbb86aea846c9ad49a24f47ca709c523c4018b584668e38b72f41"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "3d7d4cda73d6bde134a568ccbe4e8d2e7fbe701570012b71fa45acdb2258c823"

[[files]]
file = "configureddefaults/config/inventoryprofilesnext/inventoryprofiles.json"
hash = "66a9ce3a46254fcef4c29ee3d0bbd89831be30b930386c92ba9eda63b1176885"

[[files]]
file = "configureddefaults/config/xaerominimap.txt"
hash = "f25f4d1830092625e59c9274257141a35808a8fa830c329249f70a3b63e41564"

[[files]]
file = "configureddefaults/config/xaerominimap_entities.json"
hash = "1b4d2051062e0d05e4650ee5658e4c4b2ffa13236dbe584349642fc2fff6f967"

[[files]]
file = "configureddefaults/config/xaeroworldmap.txt"
hash = "6cae8c6c64eeebf4dd15076b8f172a440bf1ece460aef63d3abe206e2d45fe8f"

[[files]]
file = "configureddefaults/options.txt"
hash = "d8f8d4cc25a968e743c399a0a8019cc824dfc77fa22a69dfbd9159cb20ebdace"

[[files]]
file = "icon.png"
hash = "27644ce288db6f8ceb7fadc475b16df50d7c554351299e027aa861488721e971"

[[files]]
file = "mods/amendments.pw.toml"
hash = "61ab7794e676f45410312efe39c2cc6edf5835f4d7fa5ab685be0c0e4b78f984"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "9a9d6bf3715b20cbf83b967e4dd8b77972d1256e52a7b1c2bbfa4122f5acc931"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "e1f4a53e3e52b534add5dd018597fefd345d9bd6350b9c46ef0ec281fc62af8e"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "9b1610cd28c49d34ce2fd760d208fb569f0e20055fee4c81ed4da6489b340312"
metafile = true

[[files]]
file = "mods/blocks-bogies.pw.toml"
hash = "e94f595a5a63fdabe834b84904695ccca3f9bac8856c98b57abd8687555dc213"
metafile = true

[[files]]
file = "mods/carrasconlib.pw.toml"
hash = "308c15673753d122338836df7432147d38f1c3c35f839da4b6e1c33d0190d8e8"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "667344dcc91381c11ea871326f828a72e3386dfc450b7e08ca1ea409f66cc2d3"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8629fe0739a2243641a1a00b103682bcb2741a9295f9eac4c2a2135a867f8442"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "24c6c3fe917ffbcef04e788dec3e003d0ed03433bc00f9cf4f23fe9b85636aa7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "edccf044df3d6519c3f8cb35e1044687d1b5bdc676fdce919d0844a4d2515685"
metafile = true

[[files]]
file = "mods/connected-glass.pw.toml"
hash = "376b22883dd4642dee7bf1e727440cb01d87d72293952a1ddf0c2f1c25fa7863"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "e002fab16a9b9ef0a35844030339612a38d3c58b0b93e97a34eb43ddc9108be7"
metafile = true

[[files]]
file = "mods/create-cafe.pw.toml"
hash = "cc4adda40330d5c792ae31f364b17f56a6a68b8967d1a98dd4e49ababb1ab287"
metafile = true

[[files]]
file = "mods/create-ccbr.pw.toml"
hash = "2c0a8e956e3a1508d12544d59db0db04df6d88460dc56b80a1a8b4bdf1266005"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "a10ca44e38b499dd749e8522b51f16815ddbb60483806a58b0845f179b6b8440"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "87ccbd409962ea48348bd005f00a7c68d2add8528cdc6287c83ff52d21dc8c98"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "ed5a88a8d97fe38cca25a42aa1ffcaf51f8f84535f872a9446eff96b92b5722a"
metafile = true

[[files]]
file = "mods/create-dreams-and-desires.pw.toml"
hash = "80d8e54420806a0cfdc113dc559ae2e6bfa7dfcf44e176c7e230d7d371ca99e1"
metafile = true

[[files]]
file = "mods/create-easy-structures.pw.toml"
hash = "1d91b46a5973bda84e2b314878693ef5df83475b95569a75b00de096edfe3df4"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "7c07f70035a9ef0fa613bb1acab3db9377a7de11461761c4a33a52df71382c23"
metafile = true

[[files]]
file = "mods/create-food.pw.toml"
hash = "946a389729193083c0f937e22f778be1e88f7429bdd25abefb22316af49d7da5"
metafile = true

[[files]]
file = "mods/create-garnished.pw.toml"
hash = "c858a76c62530e6620d028776b503e291890fce7540c3fdd6daf2bd2c54538ab"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
hash = "1d8fce350ce2671f24579691c47bc178ee7b644751ecec5f068427058de0cd2b"
metafile = true

[[files]]
file = "mods/create-let-the-adventure-begin.pw.toml"
hash = "fa27a4afae3c0329580d41893390307f2f4e71e3f3d7e06c6ee19ec44de39a53"
metafile = true

[[files]]
file = "mods/create-railways-navigator.pw.toml"
hash = "ec69488edd55f31c6fc57cac9bab713a14394d1f63054cc4e2e5efc19a55abb9"
metafile = true

[[files]]
file = "mods/create-structures-arise.pw.toml"
hash = "251db2b84b5263ac874858f76fa4aabfc5ecf5df2636151c4ad5c59ffc7c1460"
metafile = true

[[files]]
file = "mods/create-train-parts.pw.toml"
hash = "c8d8e3d2cbb61f6977d475b0203ad21ef0aab34409cdc304db87a7dd65fbeda1"
metafile = true

[[files]]
file = "mods/create-trainutilities.pw.toml"
hash = "70f4abe6b7351bab4fa130e15eac677e01a87ac4ab0348150590227de8343884"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "84033f53f275811750cf65ca9ddb5ca0daeced93700ce025d2b834c115ae05f4"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "4d80daa8eb0ddcda79a42749ad4539de6cf00df3b8aa0fb12ad8a6601125b388"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/dragonlib.pw.toml"
hash = "7f37f1846f25e9c4e9297ba1e06fe81584145f466eb5b3e45940717b0aeb3bbb"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "98e02478bc3be30b8eb4e62b8fb116a5805caea3cf557f17d36c633d840fe223"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "b9244dca740d333c22f3425991fdd2fd40d3ae12384079a40a6fb7d4bca18a18"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "dfc5252f31339a2f2b900399802f2e787ebe4d6e061bd150aaef50a20d2a6d20"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "c67d73440c55cc47a47ac8987da9cd01de3ad2a8f1480a304355c3e21092d2e4"
metafile = true

[[files]]
file = "mods/factory-blocks.pw.toml"
hash = "36cc04059e9287c087425d5e3f156b2198817e32f38a2974ccade586939e96bc"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "2d7e927b0efdc5e79a50505151975605b355d14d7da2a475aa8a767697911651"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "35e72c6577b301ac850a959bce08ca1c8a68e58f7819191a61d20c7af536ee5d"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "0004feab868f7b873c12db05aae0d0dac6c87b497490b48bb66480e7c8d0f340"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "8f1bcd5781c09e0929dd109bbd7cbb4636641dee96441cf125f279f328708268"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "054a1887da4f14b791910660a2a7a2035ac1382461b881a65fe07b224c03735f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/l_enders-cataclysm.pw.toml"
hash = "0ba45c4cf0d0c605841b708a23417668e1ee4c9860a1d4572b122d6348c113ed"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "170212f0b41fc84d5d75248ad0f16f21be8079494e03c517d985fe9034196cff"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "b821efc793dd7308be6788095bea26a2a0479f9a3ddc3b0d6a6a2af351153fc0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7b8e8af83e8583adc91b2d859e5355f1bd0516a346d2584b8b01c004467d18af"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "09162fdcca41f55e16be2b2101239f1d1b138732c3b3bc2b6d70beaca99cc000"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "9dff522b00f5269538d0351536f34b22384996de30be454ef1369f1b1e5c1aeb"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "44b52fc7e10142b0f514c66dbc0c74a0feae35ee329c37454e08aa1187d1d60e"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "5c5a98c63fc8d7882eca391942741727f7c51c87fa5f48f6f91cebbd1d6e3e0f"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "34af73fbc06558118a046d6c4c26a555337f5e971ba59b42ca13471c57127f1f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "9d4e4bd1007b5529b2b35439d00d74f0554f2bd8ae0d4d72aeab9d8063c60beb"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "573f309a1bd1c410d149b6830aeddee7313e0698ac249a94f63a7e95c0eb146e"
metafile = true

[[files]]
file = "mods/pretty-in-pink.pw.toml"
hash = "d68dc1f0a4d96cfb3d947925daf7a66b97ecf356e9da21a0ee0646bf3390c634"
metafile = true

[[files]]
file = "mods/regions-unexplored.pw.toml"
hash = "5a9dcbd1981e1dff0cef24186005c0235e983841e76c22f6ed7262c1ae8e30e5"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "6b100c6847b82f48ac150816c2e9ce8fd590a4dc92a49e38634b7f6c6b5a2e71"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "a2028f1fdc803760a29877b07b2958cecdc6402eb946f9d5a0fff9fe72b8671d"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "8ed3c58f23d9255343a590b90e1216ac58142b920c9bffdd14c7fdc32e3ee002"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "55c8056ba1454acf25252ec1c7d3a33bb59c9bd8273f28f6e0402e542073ce16"
metafile = true

[[files]]
file = "mods/structure-credits.pw.toml"
hash = "12d0d7a2bd4522d394fce37639988b3ce075e714994a07ea95ffb143b6e9ffd9"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "2c297fb87d09bd4203399e865d48a10aa82016c53b6767b10b43726e111a3566"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "2e4c8891ec22ca246b414728493ff52fe177bc9c4369ed23a5a80e8332e79c67"
metafile = true

[[files]]
file = "mods/teleport-commands.pw.toml"
hash = "4069c2ead5632415da835ba6043097ddf0f0c3ca8a52caad76a20b116217ab4f"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "mods/tmrv.pw.toml"
hash = "9a2c112447329f1daea6cda77d68d3cdf7f292ae9e72f69adbfc18cb18ab1eeb"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "cdffc74140a6d0da190aebf074d7b0e1a2d7f0b0e4fa7803618d2f154c262a0b"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "539ade06248a343e6986c76c4bd88fb3d22517185bb19d768600fe51417a3255"
metafile = true

[[files]]
file = "mods/xaero-train-map.pw.toml"
hash = "055508f48abfc3dc9705337d324fe839bbc88cd5cd06ce77f65b4bd2c976a983"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "634130ab233121c290fdb2567afd3939af6d98760c11f14db0426b64b8955894"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "4c2830674a08ec9f10af13e4d259aa60158bd306a3996d935e678281ec0cb5fd"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "902c397d5dfc69b497681ba71aa5b8a8a85479b1ccf25157867e4803c16dd65b"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "ee63a5958eb1e0238257e2064d917bdaf8e528a47904bdfbe04a5758a1537e9f"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "0cc13a86488cf89d2989edc1636fa63c7efa2fe819246d42af35113458d5ba5b"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "c0e40691651465b4eb1037749148c2078123604195e19b582dbef3cd5914e3b1"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "9492d0854c51570bf2a6bace6267262e7573b94c40d721348996617e5d99480a"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "1a33e6d64e88ad59b65d126c6457d582e62724167349ea184eb237435298985e"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "e2b23d0a1bf228d37ff8c3330150c24eb19cb875e113fae543191f34ded92ff8"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "9d9b074b2425fc4f19808b7d6df4a0baeae39a37e909107aaa85004df1a2d195"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "2541b092b92a82757e5d200a6093658e20db548bb8583abad3f4506ed04e5ce6"
metafile = true

[[files]]
file = "resourcepacks/tuxblock/assets/minecraft/texts/splashes.txt"
hash = "5f6b06c32d829905c41de2cd2a1fb76e8d63823bd2e9e704221429b2fcc4c4be"

[[files]]
file = "resourcepacks/tuxblock/icon.png"
hash = "27644ce288db6f8ceb7fadc475b16df50d7c554351299e027aa861488721e971"

[[files]]
file = "resourcepacks/tuxblock/pack.mcmeta"
hash = "708cd199632de5fee85738288f638e91b73305dced6c4a3e3e0c96c40575475f"

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true
