name = "tuxblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c4b3dfd4a76073d156fef0bd929364303db1e2cfea885af3e7e77eba3f69eaf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
