name = "tuxblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "972de2c7f1e03121c8e85de0d1c8ac86d6209feaa43a279756d96ab58a298ed0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
