name = "tuxblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8c86552c2d8717b765578f6afcfccbebd656a33797cafcf7303fae6ab638d26"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
