name = "tuxblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa5a196eb1d0ef739c37896305fc9a4082391874e7b1a14373bc59bd8ada3301"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
