name = "tuxblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b856f0b7feddff2e6217e2bc94780c24eda72f0c12148109071d736613ebc585"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
