name = "tuxblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9a09d599861d862a99f5381192e5452aac135e761cf3f502654dd638105c937"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
