name = "tuxblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "759386dcb0f05f6939b9c89254ddca4f1d6696f7edf320d60582aded21f6e431"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
