name = "tuxblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a7410360bc86417674285c7a44add397f61daf66d00c50413e796e4a62ef96d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
