name = "tuxblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aec6fdddabc6e4b61280fbbe406fd5ef042b544be4980e1d355983c2eee9b753"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
